# {{KNOWLEDGE_TITLE}}

This starter package was generated by `agentpm init --kind knowledge --mode vector`.

## What this scaffold is for

This scaffold is for `mode: "vector"` Knowledge packages: prepared retrieval corpora with chunks, sources, vectors, and a local index built later by AgentPM.

## What to edit next

- Replace `knowledge/chunks.jsonl` with your prepared chunk data.
- Replace `knowledge/sources.jsonl` with your prepared source metadata.
- Add your precomputed vector payload at `knowledge/embeddings/default.f32`.
- Update `agent.json` embedding and retrieval metadata to match your corpus.
  In particular, update `knowledge.embedding.dimensions` if your vectors are not 1536-dimensional.
- Run `agentpm lint`.
- Run `agentpm knowledge build` to validate the prepared files and generate the local index metadata before publishing.

## Notes

- This starter does not include `knowledge/indexes/default`; that is generated later by `agentpm knowledge build`.
- AgentPM does not generate embeddings for this scaffold. The vector payload is expected to come from your own preparation pipeline.
