# {{KNOWLEDGE_TITLE}}

This starter package was generated by `agentpm init --kind knowledge --mode context`.

## What this scaffold is for

This scaffold is for `mode: "context"` Knowledge packages: direct context documents intended to be loaded into an agent or runtime context window without chunking, embeddings, or a retrieval index.

## What to edit next

- Replace `knowledge/docs/context.md` with your real context document content.
- Update `agent.json` document metadata if you want to add more declared files.
- Run `agentpm lint`.
- Run `agentpm knowledge build` before publishing so derived document metadata can be written back into the manifest.

## Notes

- Context-mode Knowledge packages do not require chunks, vectors, or indexes.
- Keep declared document paths package-relative and inside the package root.
