# {{LOOP_TITLE}}

This starter package was generated by `agentpm init --kind loop`.

## What this scaffold is for

This scaffold is for a Loop package: a portable control-flow contract that defines bounded phases, transitions, checkpoints, and failure handling for a consuming runtime or agent system.

## Files in this starter

- `agent.json`: the authored Loop manifest.
- `README.md`: package documentation for authors and consumers.

## What to edit next

- Update the phase IDs, objectives, and transition graph to match the control flow you want to package.
- Replace or extend the starter review loop if your runtime needs a different iterative pattern.
- Adjust checkpoints and failure policy to reflect the review and escalation boundaries your runtime should honor.
- Run `agentpm lint` to validate the Loop contract.

## Notes

- This starter defines authored loop structure only; it does not execute a runtime loop by itself.
- Checkpoints describe required decision boundaries, but approval UX and enforcement belong to the consuming runtime.
- Keep package documentation in `README.md`; the structured control-flow contract lives in `agent.json`.
