# {{MEMORY_TITLE}}

This starter package was generated by `agentpm init --kind memory`.

## What this scaffold is for

This scaffold is for a Memory Blueprint: an authored contract that defines durable memory structure, retrieval shape, and lifecycle policy for downstream runtimes.

## Files in this starter

- `agent.json`: the authored Memory Blueprint manifest.
- `schemas/user-preference.schema.json`: the authored Draft 2020-12 content schema for the starter record type.
- `README.md`: author guidance for building, inspecting, and publishing the blueprint.

## What to edit next

- Update `agent.json` to reflect your real scopes, record types, spaces, and optional lifecycle operations.
- Replace `schemas/user-preference.schema.json` with the structured content schema your runtime should persist.
- Run `agentpm lint` to validate the authored blueprint and referenced schema files.
- Run `agentpm memory build` to generate resolved record contracts under `memory/contracts/` and build metadata at `memory/build.json`.
- Run `agentpm memory inspect .` after building to review the authored model and generated contract inventory.

## Publish readiness

- `agentpm init --kind memory` creates authored files only.
- `agentpm memory build` is required before `agentpm publish`.
- The generated `memory/` directory is build output; do not hand-edit it.

## Notes

- This blueprint does not provide a live memory store or runtime CRUD implementation.
- Keep schema paths package-relative and inside the package root.
- Use ordinary Draft 2020-12 JSON Schema plus supported `x-agentpm-*` governance annotations where needed.
