# {{PROFILE_TITLE}}

This starter package was generated by `agentpm init --kind profile`.

## What this scaffold is for

This scaffold is for an Instruction Profile: a structured package of behavioral metadata describing role, objectives, communication style, boundaries, and constraints for a consuming runtime or agent system.

## Files in this starter

- `agent.json`: the authored structured Instruction Profile contract.
- `README.md`: package documentation for authors and consumers.

## Instruction Profiles vs Skills

- Use an Instruction Profile for stable behavioral guidance such as role, tone, boundaries, and durable constraints.
- Use a Skill for reusable task know-how, procedures, scripts, references, and optional Tool relationships.

## What to edit next

- Update the `profile.identity.role` field to match the behavioral role you want to package.
- Expand objectives, communication guidance, boundaries, and optional constraints to match the intended behavior.
- Run `agentpm lint` to validate the structured Profile contract.

## Notes

- Constraints in this package express author intent; they are not runtime enforcement guarantees.
- `README.md` is package documentation and is not part of the structured behavioral contract consumed by runtimes or SDK loaders.
- This starter does not generate instructions, prompts, scripts, references, or build output.
