#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/harness-m19-test/workspace"

pkg_root() {
  local kind="$1"
  local owner="$2"
  local name="$3"
  local version="$4"
  printf '%s/.agentpm/%s/%s/%s/%s' "$WORK" "$kind" "$owner" "$name" "$version"
}

write_json() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat >"$path"
}

rm -rf "$ROOT/harness-m19-test"
mkdir -p "$WORK"

cat >"$ROOT/harness-m19-test/env.sh" <<SH
export M19_ROOT="$ROOT/harness-m19-test"
export M19_WORK="$WORK"
export APM="$ROOT/target/debug/agentpm"
SH

cat >"$ROOT/harness-m19-test/README.md" <<'MD'
# Harness M19 TUI Manual Workspace

Generated by `scripts/setup-harness-m19-manual.sh`.

```bash
source harness-m19-test/env.sh
cargo build -p agentpm-cli
(cd "$M19_WORK" && "$APM" harness)
```

Useful quick checks:

```bash
(cd "$M19_WORK" && "$APM" harness --json)
TERM=dumb "$APM" harness --config "$M19_WORK/agentpm.harness.json"
```

The generated directory is ignored by git and can be deleted/regenerated at any time.
MD

cat >"$WORK/context.md" <<'MD'
# M19 TUI Manual Context

This context file exists so the left readiness rail can show Consumer Context metadata.
MD

write_json "$WORK/agentpm.harness.json" <<'JSON'
{
  "version": 1,
  "model": {
    "provider": "openai",
    "model": "gpt-4o-mini"
  },
  "scopes": {
    "user": "m19-user"
  },
  "runtime": {
    "state_dir": ".agentpm-state-m19"
  },
  "trace": {
    "enabled": true,
    "level": "normal",
    "content": "redacted"
  },
  "ui": {
    "branding": {
      "name": "Acme Operations",
      "subtitle": "M19 TUI fixture",
      "accent": "#0EA5E9"
    }
  }
}
JSON

write_json "$WORK/agent.json" <<'JSON'
{
  "kind": "agent",
  "name": "@zack/m19-tui-agent",
  "version": "0.1.0",
  "description": "Manual fixture Agent for the M19 TUI shell.",
  "tools": ["@zack/m19-search@0.1.0", "@zack/m19-comment@0.1.0"],
  "skills": ["@zack/m19-skill@0.1.0"],
  "knowledge": ["@zack/m19-guide@0.1.0"],
  "memory": ["@zack/m19-memory@0.1.0"],
  "profiles": ["@zack/m19-style@0.1.0"],
  "loop": "@zack/m19-loop@0.1.0",
  "bindings": {
    "consumer_context": { "file": "context.md" },
    "global": {
      "knowledge": ["@zack/m19-guide"],
      "profiles": ["@zack/m19-style"],
      "skills": ["@zack/m19-skill"],
      "memory": [
        { "package": "@zack/m19-memory", "spaces": ["current_note"] }
      ]
    },
    "phases": {
      "inspect": { "tools": ["@zack/m19-search"] },
      "respond": { "tools": ["@zack/m19-comment"] }
    },
    "mcp": [
      { "id": "public-tools", "tools": ["@zack/m19-search"] }
    ]
  }
}
JSON

write_json "$(pkg_root loops zack m19-loop 0.1.0)/agent.json" <<'JSON'
{
  "kind": "loop",
  "name": "@zack/m19-loop",
  "version": "0.1.0",
  "description": "Two phase manual TUI loop.",
  "loop": {
    "entry_phase": "inspect",
    "phases": [
      {
        "id": "inspect",
        "objective": "Inspect the request.",
        "outcomes": [
          { "id": "respond", "description": "Draft a response." },
          { "id": "handoff", "description": "Hand off." }
        ]
      },
      {
        "id": "respond",
        "objective": "Respond to the operator.",
        "outcomes": [
          { "id": "done", "description": "Finish the run." }
        ]
      }
    ],
    "transitions": [
      { "from": "inspect", "on": "respond", "to": "respond" },
      { "from": "inspect", "on": "handoff", "to": "$handoff" },
      { "from": "respond", "on": "done", "to": "$end" }
    ]
  }
}
JSON

for tool in m19-search m19-comment; do
  write_json "$(pkg_root tools zack "$tool" 0.1.0)/agent.json" <<JSON
{
  "kind": "tool",
  "name": "@zack/$tool",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture tool.",
  "entrypoint": {
    "command": "python3",
    "args": ["tool.py"],
    "cwd": ".",
    "timeout_ms": 1000,
    "env": {}
  },
  "inputs": {
    "type": "object",
    "properties": {
      "query": { "type": "string" }
    }
  },
  "outputs": { "type": "object" }
}
JSON
  cat >"$(pkg_root tools zack "$tool" 0.1.0)/tool.py" <<'PY'
import json, sys
payload = json.load(sys.stdin)
print(json.dumps({"ok": True, "input": payload}))
PY
done

write_json "$(pkg_root skills zack m19-skill 0.1.0)/agent.json" <<'JSON'
{
  "kind": "skill",
  "name": "@zack/m19-skill",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture skill.",
  "tools": ["@zack/m19-search@0.1.0"],
  "skill": {
    "entrypoint": "SKILL.md",
    "references": []
  }
}
JSON
cat >"$(pkg_root skills zack m19-skill 0.1.0)/SKILL.md" <<'MD'
# M19 Skill

Use concise operational language.
MD

GUIDE_ROOT="$(pkg_root knowledge zack m19-guide 0.1.0)"
write_json "$GUIDE_ROOT/agent.json" <<'JSON'
{
  "kind": "knowledge",
  "name": "@zack/m19-guide",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture guide.",
  "knowledge": {
    "mode": "context",
    "content_type": "text/markdown",
    "documents": [
      { "path": "knowledge/docs/guide.md", "content_type": "text/markdown" }
    ]
  }
}
JSON
mkdir -p "$GUIDE_ROOT/knowledge/docs"
cat >"$GUIDE_ROOT/knowledge/docs/guide.md" <<'MD'
# M19 Guide

This package exists to light up Knowledge readiness in the TUI.
MD

MEMORY_ROOT="$(pkg_root memory zack m19-memory 0.1.0)"
write_json "$MEMORY_ROOT/agent.json" <<'JSON'
{
  "kind": "memory",
  "name": "@zack/m19-memory",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture Memory Blueprint.",
  "memory": {
    "scopes": {
      "user": { "description": "The operator using the manual fixture." }
    },
    "record_types": {
      "note": {
        "schema": "schemas/note.schema.json",
        "version": "1.0.0",
        "description": "A note."
      }
    },
    "spaces": {
      "current_note": {
        "model": "document",
        "scope": ["user"],
        "retrieval": { "modes": ["key"] },
        "description": "Current note document.",
        "record_types": ["note"]
      }
    }
  }
}
JSON
write_json "$MEMORY_ROOT/schemas/note.schema.json" <<'JSON'
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "body": { "type": "string" }
  },
  "required": ["body"],
  "additionalProperties": false
}
JSON
write_json "$MEMORY_ROOT/memory/build.json" <<'JSON'
{ "schema_version": 1, "generated_by": "m19-manual-fixture" }
JSON
write_json "$MEMORY_ROOT/memory/contracts/index.json" <<'JSON'
{
  "contracts": [
    { "path": "memory/contracts/current_note.note.schema.json" }
  ]
}
JSON
write_json "$MEMORY_ROOT/memory/contracts/current_note.note.schema.json" <<'JSON'
{
  "type": "object",
  "properties": {
    "body": { "type": "string" }
  },
  "required": ["body"],
  "additionalProperties": false
}
JSON

write_json "$(pkg_root profiles zack m19-style 0.1.0)/agent.json" <<'JSON'
{
  "kind": "profile",
  "name": "m19-style",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture Profile.",
  "profile": {
    "identity": {
      "role": "Operations assistant",
      "description": "Helps operators inspect Harness behavior.",
      "expertise": ["incident response"]
    },
    "objectives": ["Keep output concrete."],
    "principles": ["Name uncertainty."],
    "audience": {
      "description": "AgentPM developers.",
      "assumed_knowledge": "Harness basics.",
      "adaptation": ["Prefer concise summaries."]
    },
    "communication": {
      "tone": ["calm"],
      "verbosity": "concise",
      "guidelines": ["Use concrete nouns."],
      "formatting": ["Short paragraphs."],
      "vocabulary": {
        "prefer": ["ready"],
        "avoid": ["magic"]
      }
    },
    "boundaries": ["Do not claim execution happened unless it did."],
    "constraints": [
      {
        "id": "cite-state",
        "strength": "required",
        "instruction": "Tie status to visible Harness state."
      }
    ]
  }
}
JSON

write_json "$WORK/agent.lock" <<'JSON'
{
  "lockfile_version": 3,
  "generated": "2026-09-18T00:00:00Z",
  "packages": {
    "tool:@zack/m19-search@0.1.0": {
      "kind": "tool",
      "name": "@zack/m19-search",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "tool:@zack/m19-comment@0.1.0": {
      "kind": "tool",
      "name": "@zack/m19-comment",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "skill:@zack/m19-skill@0.1.0": {
      "kind": "skill",
      "name": "@zack/m19-skill",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "knowledge:@zack/m19-guide@0.1.0": {
      "kind": "knowledge",
      "name": "@zack/m19-guide",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "memory:@zack/m19-memory@0.1.0": {
      "kind": "memory",
      "name": "@zack/m19-memory",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "profile:@zack/m19-style@0.1.0": {
      "kind": "profile",
      "name": "@zack/m19-style",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "loop:@zack/m19-loop@0.1.0": {
      "kind": "loop",
      "name": "@zack/m19-loop",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    }
  },
  "roots": {
    "local:agent": {
      "name": "@zack/m19-tui-agent",
      "version": "0.1.0",
      "tools": [
        "tool:@zack/m19-search@0.1.0",
        "tool:@zack/m19-comment@0.1.0"
      ],
      "skills": ["skill:@zack/m19-skill@0.1.0"],
      "knowledge": ["knowledge:@zack/m19-guide@0.1.0"],
      "memory": ["memory:@zack/m19-memory@0.1.0"],
      "profiles": ["profile:@zack/m19-style@0.1.0"],
      "loop": "loop:@zack/m19-loop@0.1.0"
    }
  }
}
JSON

cat <<EOF
Created $ROOT/harness-m19-test

Run:
  source harness-m19-test/env.sh
  cargo build -p agentpm-cli
  (cd "\$M19_WORK" && "\$APM" harness)

Exit the TUI with q or Esc.
EOF
