#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE="$ROOT/harness-release-verify-test"
WORK="$BASE/workspace"
APPROVAL_WORK="$BASE/approval-workspace"
RUNNERS="$BASE/runners"
RUNS="$BASE/runs"
APM_BIN="$ROOT/target/debug/agentpm"
PYTHON_CMD="${AGENTPM_MANUAL_PYTHON:-python3}"

write_json() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat >"$path"
}

pkg_root() {
  local kind="$1"
  local owner="$2"
  local name="$3"
  local version="$4"
  printf '%s/.agentpm/%s/%s/%s/%s' "$WORK" "$kind" "$owner" "$name" "$version"
}

rm -rf "$BASE"
mkdir -p "$WORK" "$APPROVAL_WORK" "$RUNNERS" "$RUNS"

cat >"$BASE/env.sh" <<SH
export HARNESS_VERIFY_ROOT="$BASE"
export HARNESS_VERIFY_WORK="$WORK"
export HARNESS_VERIFY_APPROVAL_WORK="$APPROVAL_WORK"
export HARNESS_VERIFY_APPROVAL_CONFIG="$APPROVAL_WORK/agentpm.harness.json"
export HARNESS_VERIFY_RUNNERS="$RUNNERS"
export HARNESS_VERIFY_OUT="$RUNS"
export HARNESS_VERIFY_AGENT=""
export HARNESS_VERIFY_CONFIG="$WORK/agentpm.harness.json"
export HARNESS_VERIFY_SCOPE_KEY="user"
export HARNESS_VERIFY_SCOPE_VALUE="release-verify-user"
export HARNESS_VERIFY_INPUT="Check release readiness and produce the final verification answer."
export APM="$APM_BIN"
export OPENAI_API_KEY="harness-release-verify-key"
export OPENAI_BASE_URL="http://127.0.0.1:18130/v1/chat/completions"
export AGENTPM_MANUAL_PYTHON="\${AGENTPM_MANUAL_PYTHON:-$PYTHON_CMD}"
SH

cat >"$BASE/README.md" <<'MD'
# Harness Release Verification Fixture

Generated by `scripts/setup-harness-release-verification.sh`.

Use this fixture with `HARNESS_RELEASE_VERIFICATION.md`.

Start the deterministic OpenAI-compatible server before running the four surfaces:

```bash
source harness-release-verify-test/env.sh
"$AGENTPM_MANUAL_PYTHON" "$HARNESS_VERIFY_ROOT/fake_openai_server.py" \
  --port 18130 \
  --log "$HARNESS_VERIFY_OUT/provider-bodies.jsonl"
```

In another terminal, source the same `env.sh` and run the headless, Node SDK,
Python SDK, and TUI steps from `HARNESS_RELEASE_VERIFICATION.md`.
MD

cat >"$WORK/context.md" <<'MD'
# Release Verification Context

The Harness release verification scenario should inspect readiness once, carry
the phase output forward, and finish with a concise terminal answer.
MD

write_json "$WORK/agentpm.harness.json" <<'JSON'
{
  "version": 1,
  "model": {
    "provider": "openai",
    "model": "release-verifier"
  },
  "scopes": {
    "user": "release-verify-user"
  },
  "runtime": {
    "state_dir": ".agentpm-state-release-verify",
    "limits": {
      "max_steps": 4,
      "max_model_calls_per_phase": 4,
      "max_tool_calls_per_phase": 2,
      "max_actions_per_phase": 8,
      "max_structured_output_repairs": 1,
      "max_tool_call_repairs": 1
    }
  },
  "trace": {
    "enabled": true,
    "level": "verbose",
    "content": "full"
  }
}
JSON

write_json "$WORK/agent.json" <<'JSON'
{
  "kind": "agent",
  "name": "release-verify-agent",
  "version": "0.1.0",
  "description": "AgentPM Harness release verification fixture Agent.",
  "tools": ["@zack/release-lookup@0.1.0"],
  "loop": "@zack/release-verify-loop@0.1.0",
  "bindings": {
    "consumer_context": { "file": "context.md" },
    "phases": {
      "inspect": { "tools": ["@zack/release-lookup"] },
      "respond": { "tools": [] }
    }
  }
}
JSON

write_json "$(pkg_root loops zack release-verify-loop 0.1.0)/agent.json" <<'JSON'
{
  "kind": "loop",
  "name": "@zack/release-verify-loop",
  "version": "0.1.0",
  "description": "Two-phase release verification loop.",
  "loop": {
    "entry_phase": "inspect",
    "phases": [
      {
        "id": "inspect",
        "objective": "Inspect release readiness once using the lookup Tool, then preserve the finding for the response phase.",
        "access": {
          "tools": true,
          "knowledge": false,
          "memory": { "read": false, "write": false }
        },
        "outcomes": [
          {
            "id": "respond",
            "description": "Readiness was inspected and the response phase should answer from the preserved finding."
          }
        ]
      },
      {
        "id": "respond",
        "objective": "Answer from the inspect phase output without re-running investigation.",
        "access": {
          "tools": false,
          "knowledge": false,
          "memory": { "read": false, "write": false }
        },
        "outcomes": [
          {
            "id": "done",
            "description": "The release verification answer is complete."
          }
        ]
      }
    ],
    "transitions": [
      { "from": "inspect", "on": "respond", "to": "respond" },
      { "from": "respond", "on": "done", "to": "$end" }
    ]
  }
}
JSON

write_json "$(pkg_root tools zack release-lookup 0.1.0)/agent.json" <<JSON
{
  "kind": "tool",
  "name": "@zack/release-lookup",
  "version": "0.1.0",
  "description": "Deterministic release verification lookup Tool.",
  "entrypoint": {
    "command": "$PYTHON_CMD",
    "args": ["tool.py"],
    "cwd": ".",
    "timeout_ms": 1000,
    "env": {}
  },
  "inputs": {
    "type": "object",
    "additionalProperties": false,
    "required": ["query"],
    "properties": {
      "query": { "type": "string" }
    }
  },
  "outputs": {
    "type": "object",
    "additionalProperties": false,
    "required": ["ready", "summary"],
    "properties": {
      "ready": { "type": "boolean" },
      "summary": { "type": "string" }
    }
  }
}
JSON

cat >"$(pkg_root tools zack release-lookup 0.1.0)/tool.py" <<'PY'
#!/usr/bin/env python3
import json
import sys

payload = json.load(sys.stdin)
print(json.dumps({
    "ready": True,
    "summary": "Release verification fixture lookup completed for " + payload.get("query", "release readiness"),
}))
PY
chmod +x "$(pkg_root tools zack release-lookup 0.1.0)/tool.py"

write_json "$WORK/agent.lock" <<'JSON'
{
  "lockfile_version": 3,
  "generated": "2026-09-26T00:00:00Z",
  "packages": {
    "tool:@zack/release-lookup@0.1.0": {
      "kind": "tool",
      "name": "@zack/release-lookup",
      "version": "0.1.0",
      "integrity": "sha256-release-verify"
    },
    "loop:@zack/release-verify-loop@0.1.0": {
      "kind": "loop",
      "name": "@zack/release-verify-loop",
      "version": "0.1.0",
      "integrity": "sha256-release-verify"
    }
  },
  "roots": {
    "local:agent": {
      "name": "release-verify-agent",
      "version": "0.1.0",
      "tools": [
        "tool:@zack/release-lookup@0.1.0"
      ],
      "loop": "loop:@zack/release-verify-loop@0.1.0"
    }
  }
}
JSON

cat >"$APPROVAL_WORK/context.md" <<'MD'
# Approval Verification Context

The headless approval-required scenario should stop before the gated review
phase because no interactive approval controller is available.
MD

write_json "$APPROVAL_WORK/agentpm.harness.json" <<'JSON'
{
  "version": 1,
  "model": {
    "provider": "openai",
    "model": "release-verifier"
  },
  "scopes": {
    "user": "release-verify-user"
  },
  "runtime": {
    "state_dir": ".agentpm-state-release-verify-approval",
    "limits": {
      "max_steps": 4,
      "max_model_calls_per_phase": 4,
      "max_tool_calls_per_phase": 2,
      "max_actions_per_phase": 8,
      "max_structured_output_repairs": 1,
      "max_tool_call_repairs": 1
    }
  },
  "trace": {
    "enabled": true,
    "level": "verbose",
    "content": "full"
  }
}
JSON

write_json "$APPROVAL_WORK/agent.json" <<'JSON'
{
  "kind": "agent",
  "name": "release-verify-approval-agent",
  "version": "0.1.0",
  "description": "AgentPM Harness release verification approval fixture Agent.",
  "tools": [],
  "loop": "@zack/release-approval-loop@0.1.0",
  "bindings": {
    "consumer_context": { "file": "context.md" }
  }
}
JSON

write_json "$APPROVAL_WORK/.agentpm/loops/zack/release-approval-loop/0.1.0/agent.json" <<'JSON'
{
  "kind": "loop",
  "name": "@zack/release-approval-loop",
  "version": "0.1.0",
  "description": "Two-phase release verification loop with an approval checkpoint.",
  "loop": {
    "entry_phase": "assess",
    "checkpoints": [
      {
        "id": "approve-release-review",
        "type": "approval",
        "before_phase": "review",
        "on_reject": "$handoff"
      }
    ],
    "phases": [
      {
        "id": "assess",
        "objective": "Assess whether the release readiness answer should enter review.",
        "access": {
          "tools": false,
          "knowledge": false,
          "memory": { "read": false, "write": false }
        },
        "outcomes": [
          {
            "id": "review",
            "description": "The answer is ready for the gated review phase."
          }
        ]
      },
      {
        "id": "review",
        "objective": "Review the release readiness answer after approval.",
        "access": {
          "tools": false,
          "knowledge": false,
          "memory": { "read": false, "write": false }
        },
        "outcomes": [
          {
            "id": "done",
            "description": "The approved review is complete."
          }
        ]
      }
    ],
    "transitions": [
      { "from": "assess", "on": "review", "to": "review" },
      { "from": "review", "on": "done", "to": "$end" }
    ]
  }
}
JSON

write_json "$APPROVAL_WORK/agent.lock" <<'JSON'
{
  "lockfile_version": 3,
  "generated": "2026-09-26T00:00:00Z",
  "packages": {
    "loop:@zack/release-approval-loop@0.1.0": {
      "kind": "loop",
      "name": "@zack/release-approval-loop",
      "version": "0.1.0",
      "integrity": "sha256-release-verify-approval"
    }
  },
  "roots": {
    "local:agent": {
      "name": "release-verify-approval-agent",
      "version": "0.1.0",
      "tools": [],
      "loop": "loop:@zack/release-approval-loop@0.1.0"
    }
  }
}
JSON

cat >"$BASE/fake_openai_server.py" <<'PY'
#!/usr/bin/env python3
import argparse
import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path


parser = argparse.ArgumentParser()
parser.add_argument("--host", default="127.0.0.1")
parser.add_argument("--port", type=int, default=18130)
parser.add_argument("--log", type=Path, required=True)
args = parser.parse_args()

args.log.parent.mkdir(parents=True, exist_ok=True)
sequence = 0


def write_log(path, body):
    global sequence
    sequence += 1
    with args.log.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps({"sequence": sequence, "path": path, "body": body}, sort_keys=True) + "\n")


def tool_names(body):
    names = []
    for tool in body.get("tools") or []:
        function = tool.get("function") or {}
        name = function.get("name")
        if isinstance(name, str):
            names.append(name)
    return names


def phase_outcomes(body):
    for tool in body.get("tools") or []:
        function = tool.get("function") or {}
        if function.get("name") != "phase_complete":
            continue
        parameters = function.get("parameters") or {}
        outcome = ((parameters.get("properties") or {}).get("outcome") or {})
        enum = outcome.get("enum") or []
        return [str(value) for value in enum]
    return []


def has_tool_result(body):
    for message in body.get("messages") or []:
        if message.get("role") == "tool":
            return True
    return False


def response_with_tool(alias, call_id, arguments, text=None):
    return {
        "id": "chatcmpl-release-verify",
        "object": "chat.completion",
        "choices": [{
            "index": 0,
            "message": {
                "role": "assistant",
                "content": text,
                "tool_calls": [{
                    "id": call_id,
                    "type": "function",
                    "function": {
                        "name": alias,
                        "arguments": json.dumps(arguments),
                    },
                }],
            },
            "finish_reason": "tool_calls",
        }],
        "usage": {"prompt_tokens": 10, "completion_tokens": 5, "total_tokens": 15},
    }


def response_for(body):
    names = tool_names(body)
    outcomes = phase_outcomes(body)
    action_tools = [name for name in names if name != "phase_complete"]
    if "respond" in outcomes and action_tools and not has_tool_result(body):
        return response_with_tool(
            action_tools[0],
            f"call_release_lookup_{sequence}",
            {"arguments": {"query": "release readiness"}},
            "I will inspect release readiness once.",
        )
    if "respond" in outcomes:
        return response_with_tool(
            "phase_complete",
            f"call_release_respond_{sequence}",
            {
                "outcome": "respond",
                "output": {
                    "ready": True,
                    "summary": "Release readiness was inspected once and is ready for response.",
                },
            },
        )
    if "done" in outcomes:
        return response_with_tool(
            "phase_complete",
            f"call_release_done_{sequence}",
            {
                "outcome": "done",
                "output": {
                    "answer": "Release verification completed successfully from the preserved inspect output.",
                },
            },
        )
    return response_with_tool(
        "phase_complete",
        f"call_release_complete_{sequence}",
        {"outcome": outcomes[0] if outcomes else "complete", "output": {"answer": "complete"}},
    )


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/health":
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"ok")
            return
        self.send_response(404)
        self.end_headers()

    def do_POST(self):
        length = int(self.headers.get("content-length", "0"))
        body = json.loads(self.rfile.read(length) or b"{}")
        write_log(self.path, body)
        try:
            payload = json.dumps(response_for(body)).encode()
            self.send_response(200)
        except Exception as exc:
            payload = json.dumps({"error": str(exc)}).encode()
            self.send_response(500)
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt, *values):
        return


ThreadingHTTPServer((args.host, args.port), Handler).serve_forever()
PY
chmod +x "$BASE/fake_openai_server.py"

cat >"$RUNNERS/node-runner.mjs" <<'JS'
import { writeFileSync } from 'node:fs';
import { HarnessClient } from '../../../agentpm-sdk-node/dist/index.js';

const scopeKey = process.env.HARNESS_VERIFY_SCOPE_KEY;
const scopeValue = process.env.HARNESS_VERIFY_SCOPE_VALUE;
const harness = new HarnessClient({
  agent: process.env.HARNESS_VERIFY_AGENT || undefined,
  configPath: process.env.HARNESS_VERIFY_CONFIG || undefined,
  scopes: scopeKey && scopeValue ? { [scopeKey]: scopeValue } : undefined,
  cwd: process.env.HARNESS_VERIFY_WORK,
  agentpmPath: process.env.APM,
  env: {
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_BASE_URL: process.env.OPENAI_BASE_URL,
  },
});
harness.onStderr((chunk) => process.stderr.write(chunk));

try {
  const result = await harness.run(process.env.HARNESS_VERIFY_INPUT);
  writeFileSync(process.env.NODE_REPORT, JSON.stringify(result.report, null, 2) + '\n');
} finally {
  await harness.shutdown();
}
JS

cat >"$RUNNERS/node-repeated-runner.mjs" <<'JS'
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { HarnessClient } from '../../../agentpm-sdk-node/dist/index.js';

const scopeKey = process.env.HARNESS_VERIFY_SCOPE_KEY;
const scopeValue = process.env.HARNESS_VERIFY_SCOPE_VALUE;
const contextPath = join(process.env.HARNESS_VERIFY_WORK, 'context.md');
const harness = new HarnessClient({
  agent: process.env.HARNESS_VERIFY_AGENT || undefined,
  configPath: process.env.HARNESS_VERIFY_CONFIG || undefined,
  scopes: scopeKey && scopeValue ? { [scopeKey]: scopeValue } : undefined,
  cwd: process.env.HARNESS_VERIFY_WORK,
  agentpmPath: process.env.APM,
  env: {
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_BASE_URL: process.env.OPENAI_BASE_URL,
  },
});
harness.onStderr((chunk) => process.stderr.write(chunk));

try {
  writeFileSync(
    contextPath,
    '# Release Verification Context\n\nRepeated Run marker: first-run-context.\n',
  );
  const first = await harness.run(`${process.env.HARNESS_VERIFY_INPUT} First repeated Run.`);
  writeFileSync(
    process.env.NODE_REPEAT_REPORT_ONE,
    JSON.stringify(first.report, null, 2) + '\n',
  );

  writeFileSync(
    contextPath,
    '# Release Verification Context\n\nRepeated Run marker: second-run-context.\n',
  );
  const second = await harness.run(`${process.env.HARNESS_VERIFY_INPUT} Second repeated Run.`);
  writeFileSync(
    process.env.NODE_REPEAT_REPORT_TWO,
    JSON.stringify(second.report, null, 2) + '\n',
  );

  writeFileSync(
    process.env.NODE_REPEAT_SUMMARY,
    JSON.stringify(
      {
        first: {
          status: first.report.terminal_status,
          trace_path: first.report.trace_path,
          phase_count: (first.report.phase_summaries || []).length,
          action_count: (first.report.action_summaries || []).length,
        },
        second: {
          status: second.report.terminal_status,
          trace_path: second.report.trace_path,
          phase_count: (second.report.phase_summaries || []).length,
          action_count: (second.report.action_summaries || []).length,
        },
      },
      null,
      2,
    ) + '\n',
  );
} finally {
  await harness.shutdown();
}
JS

cat >"$RUNNERS/python_runner.py" <<PY
#!/usr/bin/env python3
import json
import os
import sys
import importlib.util
from pathlib import Path

spec = importlib.util.spec_from_file_location(
    "agentpm_harness_direct",
    "$ROOT/../agentpm-sdk-python/src/agentpm/harness.py",
)
if spec is None or spec.loader is None:
    raise RuntimeError("could not load Python SDK harness module")
module = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = module
spec.loader.exec_module(module)
HarnessClient = module.HarnessClient

scope_key = os.environ.get("HARNESS_VERIFY_SCOPE_KEY")
scope_value = os.environ.get("HARNESS_VERIFY_SCOPE_VALUE")
harness = HarnessClient(
    agent=os.environ.get("HARNESS_VERIFY_AGENT") or None,
    config_path=os.environ.get("HARNESS_VERIFY_CONFIG") or None,
    scopes={scope_key: scope_value} if scope_key and scope_value else None,
    cwd=os.environ["HARNESS_VERIFY_WORK"],
    agentpm_path=os.environ["APM"],
    env={
        "OPENAI_API_KEY": os.environ["OPENAI_API_KEY"],
        "OPENAI_BASE_URL": os.environ["OPENAI_BASE_URL"],
    },
)

try:
    result = harness.run(os.environ["HARNESS_VERIFY_INPUT"])
    Path(os.environ["PYTHON_REPORT"]).write_text(
        json.dumps(result["report"], indent=2) + "\\n",
        encoding="utf-8",
    )
finally:
    harness.shutdown()
PY
chmod +x "$RUNNERS/python_runner.py"

cat >"$RUNNERS/extract_trace.py" <<'PY'
#!/usr/bin/env python3
import json
import sys
from pathlib import Path

print(json.loads(Path(sys.argv[1]).read_text())["trace_path"])
PY
chmod +x "$RUNNERS/extract_trace.py"

cat <<MSG
Created Harness release verification fixture:
  $BASE

Next:
  source "$BASE/env.sh"
  "$PYTHON_CMD" "$BASE/fake_openai_server.py" --port 18130 --log "$RUNS/provider-bodies.jsonl"

In another terminal:
  source "$BASE/env.sh"
  follow HARNESS_RELEASE_VERIFICATION.md

For Node SDK verification, build the Node SDK first if needed:
  (cd "$ROOT/../agentpm-sdk-node" && pnpm build)
MSG
