#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/harness-m19-test/workspace"
DIAGNOSTICS_WORK="$ROOT/harness-m19-test/diagnostics-workspace"
MISSING_SCOPE_WORK="$ROOT/harness-m19-test/missing-scope-workspace"
MISSING_MODEL_WORK="$ROOT/harness-m19-test/missing-model-workspace"
SELECTION_WORK="$ROOT/harness-m19-test/selection-workspace"

pkg_root_at() {
  local workspace="$1"
  shift
  local kind="$1"
  local owner="$2"
  local name="$3"
  local version="$4"
  printf '%s/.agentpm/%s/%s/%s/%s' "$workspace" "$kind" "$owner" "$name" "$version"
}

pkg_root() {
  pkg_root_at "$WORK" "$@"
}

write_json() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat >"$path"
}

rm -rf "$ROOT/harness-m19-test"
mkdir -p "$WORK"

cat >"$ROOT/harness-m19-test/env.sh" <<SH
export M19_ROOT="$ROOT/harness-m19-test"
export M19_WORK="$WORK"
export M19_DIAGNOSTICS_WORK="$DIAGNOSTICS_WORK"
export M19_MISSING_SCOPE_WORK="$MISSING_SCOPE_WORK"
export M19_MISSING_MODEL_WORK="$MISSING_MODEL_WORK"
export M19_SELECTION_WORK="$SELECTION_WORK"
export APM="$ROOT/target/debug/agentpm"
SH

cat >"$ROOT/harness-m19-test/README.md" <<'MD'
# Harness M19 TUI Manual Workspace

Generated by `scripts/setup-harness-m19-manual.sh`.

## Setup

```bash
source harness-m19-test/env.sh
cargo build -p agentpm-cli
```

Each case must be run from its fixture workspace with the `cd ... && "$APM" harness` shape below. Passing `--config` from the repo root is not equivalent because Harness still uses the current directory as the workspace root.

## Cases

### 1. Clean ready workspace

Shows the normal 19A-19C TUI shell with the full readiness rail, no diagnostics, no `D Details` key, and `Page 1/1` pinned at the bottom of the Preflight panel.

```bash
(cd "$M19_WORK" && "$APM" harness)
```

### 2. Diagnostics, suppressed tool, detail toggle, and paging

Shows actual diagnostics in the Preflight panel:

- one tool with required environment variables missing
- one tool suppressed by an intentionally impossible Python runtime version
- `D Details` should appear in the bottom bar
- pressing `D` should expand diagnostic codes into full messages
- resizing the terminal shorter should produce multiple Preflight pages, with `Page N/M · Shift+1 next` pinned at the bottom
- pressing `Shift+1` should cycle pages

```bash
(cd "$M19_DIAGNOSTICS_WORK" && "$APM" harness)
```

### 3. Missing Memory scope resolution

Shows the unresolved runtime scope diagnostic and the `S Scope` action. Press `S`, enter `user=m19-user`, then press Enter. The TUI should re-run bootstrap and clear the missing-scope diagnostic.

```bash
(cd "$M19_MISSING_SCOPE_WORK" && "$APM" harness)
```

### 4. Missing model resolution

Shows the `P Model` action because the harness config intentionally omits `model`. Press `P`, enter `openai/gpt-4o-mini`, then press Enter. The TUI should re-run bootstrap with that model override.

```bash
(cd "$M19_MISSING_MODEL_WORK" && "$APM" harness)
```

### 5. Agent selection resolution

Shows the `A Agent` action because the lockfile intentionally contains two local Agent roots. Press `A`, enter either `@zack/m19-tui-agent` or `@zack/m19-alt-agent`, then press Enter. The TUI should re-run bootstrap with that selected Agent.

```bash
(cd "$M19_SELECTION_WORK" && "$APM" harness)
```

## Useful quick checks

```bash
(cd "$M19_WORK" && "$APM" harness --json)
TERM=dumb "$APM" harness --config "$M19_WORK/agentpm.harness.json"
```

The generated directory is ignored by git and can be deleted/regenerated at any time.

## Troubleshooting

If the TUI shows `Harness plan does not include a resolved Loop package`, you are probably running from the wrong current directory. Re-run the case exactly as written, for example:

```bash
(cd "$M19_DIAGNOSTICS_WORK" && "$APM" harness)
```
MD

cat >"$WORK/context.md" <<'MD'
# M19 TUI Manual Context

This context file exists so the left readiness rail can show Consumer Context metadata.
MD

write_json "$WORK/agentpm.harness.json" <<'JSON'
{
  "version": 1,
  "model": {
    "provider": "openai",
    "model": "gpt-4o-mini"
  },
  "scopes": {
    "user": "m19-user"
  },
  "runtime": {
    "state_dir": ".agentpm-state-m19"
  },
  "trace": {
    "enabled": true,
    "level": "normal",
    "content": "redacted"
  },
  "ui": {
    "branding": {
      "name": "Acme Operations",
      "subtitle": "M19 TUI fixture",
      "accent": "#0EA5E9"
    }
  }
}
JSON

write_json "$WORK/agent.json" <<'JSON'
{
  "kind": "agent",
  "name": "@zack/m19-tui-agent",
  "version": "0.1.0",
  "description": "Manual fixture Agent for the M19 TUI shell.",
  "tools": ["@zack/m19-search@0.1.0", "@zack/m19-comment@0.1.0"],
  "skills": ["@zack/m19-skill@0.1.0"],
  "knowledge": ["@zack/m19-guide@0.1.0"],
  "memory": ["@zack/m19-memory@0.1.0"],
  "profiles": ["@zack/m19-style@0.1.0"],
  "loop": "@zack/m19-loop@0.1.0",
  "bindings": {
    "consumer_context": { "file": "context.md" },
    "global": {
      "knowledge": ["@zack/m19-guide"],
      "profiles": ["@zack/m19-style"],
      "skills": ["@zack/m19-skill"],
      "memory": [
        { "package": "@zack/m19-memory", "spaces": ["current_note"] }
      ]
    },
    "phases": {
      "inspect": { "tools": ["@zack/m19-search"] },
      "respond": { "tools": ["@zack/m19-comment"] }
    },
    "mcp": [
      { "id": "public-tools", "tools": ["@zack/m19-search"] }
    ]
  }
}
JSON

write_json "$(pkg_root loops zack m19-loop 0.1.0)/agent.json" <<'JSON'
{
  "kind": "loop",
  "name": "@zack/m19-loop",
  "version": "0.1.0",
  "description": "Two phase manual TUI loop.",
  "loop": {
    "entry_phase": "inspect",
    "phases": [
      {
        "id": "inspect",
        "objective": "Inspect the request.",
        "outcomes": [
          { "id": "respond", "description": "Draft a response." },
          { "id": "handoff", "description": "Hand off." }
        ]
      },
      {
        "id": "respond",
        "objective": "Respond to the operator.",
        "outcomes": [
          { "id": "done", "description": "Finish the run." }
        ]
      }
    ],
    "transitions": [
      { "from": "inspect", "on": "respond", "to": "respond" },
      { "from": "inspect", "on": "handoff", "to": "$handoff" },
      { "from": "respond", "on": "done", "to": "$end" }
    ]
  }
}
JSON

for tool in m19-search m19-comment; do
  write_json "$(pkg_root tools zack "$tool" 0.1.0)/agent.json" <<JSON
{
  "kind": "tool",
  "name": "@zack/$tool",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture tool.",
  "entrypoint": {
    "command": "python3",
    "args": ["tool.py"],
    "cwd": ".",
    "timeout_ms": 1000,
    "env": {}
  },
  "inputs": {
    "type": "object",
    "properties": {
      "query": { "type": "string" }
    }
  },
  "outputs": { "type": "object" }
}
JSON
  cat >"$(pkg_root tools zack "$tool" 0.1.0)/tool.py" <<'PY'
import json, sys
payload = json.load(sys.stdin)
print(json.dumps({"ok": True, "input": payload}))
PY
done

write_json "$(pkg_root skills zack m19-skill 0.1.0)/agent.json" <<'JSON'
{
  "kind": "skill",
  "name": "@zack/m19-skill",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture skill.",
  "tools": ["@zack/m19-search@0.1.0"],
  "skill": {
    "entrypoint": "SKILL.md",
    "references": []
  }
}
JSON
cat >"$(pkg_root skills zack m19-skill 0.1.0)/SKILL.md" <<'MD'
# M19 Skill

Use concise operational language.
MD

GUIDE_ROOT="$(pkg_root knowledge zack m19-guide 0.1.0)"
write_json "$GUIDE_ROOT/agent.json" <<'JSON'
{
  "kind": "knowledge",
  "name": "@zack/m19-guide",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture guide.",
  "knowledge": {
    "mode": "context",
    "content_type": "text/markdown",
    "documents": [
      { "path": "knowledge/docs/guide.md", "content_type": "text/markdown" }
    ]
  }
}
JSON
mkdir -p "$GUIDE_ROOT/knowledge/docs"
cat >"$GUIDE_ROOT/knowledge/docs/guide.md" <<'MD'
# M19 Guide

This package exists to light up Knowledge readiness in the TUI.
MD

MEMORY_ROOT="$(pkg_root memory zack m19-memory 0.1.0)"
write_json "$MEMORY_ROOT/agent.json" <<'JSON'
{
  "kind": "memory",
  "name": "@zack/m19-memory",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture Memory Blueprint.",
  "memory": {
    "scopes": {
      "user": { "description": "The operator using the manual fixture." }
    },
    "record_types": {
      "note": {
        "schema": "schemas/note.schema.json",
        "version": "1.0.0",
        "description": "A note."
      }
    },
    "spaces": {
      "current_note": {
        "model": "document",
        "scope": ["user"],
        "retrieval": { "modes": ["key"] },
        "description": "Current note document.",
        "record_types": ["note"]
      }
    }
  }
}
JSON
write_json "$MEMORY_ROOT/schemas/note.schema.json" <<'JSON'
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "body": { "type": "string" }
  },
  "required": ["body"],
  "additionalProperties": false
}
JSON
write_json "$MEMORY_ROOT/memory/build.json" <<'JSON'
{ "schema_version": 1, "generated_by": "m19-manual-fixture" }
JSON
write_json "$MEMORY_ROOT/memory/contracts/index.json" <<'JSON'
{
  "contracts": [
    { "path": "memory/contracts/current_note.note.schema.json" }
  ]
}
JSON
write_json "$MEMORY_ROOT/memory/contracts/current_note.note.schema.json" <<'JSON'
{
  "type": "object",
  "properties": {
    "body": { "type": "string" }
  },
  "required": ["body"],
  "additionalProperties": false
}
JSON

write_json "$(pkg_root profiles zack m19-style 0.1.0)/agent.json" <<'JSON'
{
  "kind": "profile",
  "name": "m19-style",
  "version": "0.1.0",
  "description": "Manual M19 TUI fixture Profile.",
  "profile": {
    "identity": {
      "role": "Operations assistant",
      "description": "Helps operators inspect Harness behavior.",
      "expertise": ["incident response"]
    },
    "objectives": ["Keep output concrete."],
    "principles": ["Name uncertainty."],
    "audience": {
      "description": "AgentPM developers.",
      "assumed_knowledge": "Harness basics.",
      "adaptation": ["Prefer concise summaries."]
    },
    "communication": {
      "tone": ["calm"],
      "verbosity": "concise",
      "guidelines": ["Use concrete nouns."],
      "formatting": ["Short paragraphs."],
      "vocabulary": {
        "prefer": ["ready"],
        "avoid": ["magic"]
      }
    },
    "boundaries": ["Do not claim execution happened unless it did."],
    "constraints": [
      {
        "id": "cite-state",
        "strength": "required",
        "instruction": "Tie status to visible Harness state."
      }
    ]
  }
}
JSON

write_json "$WORK/agent.lock" <<'JSON'
{
  "lockfile_version": 3,
  "generated": "2026-09-18T00:00:00Z",
  "packages": {
    "tool:@zack/m19-search@0.1.0": {
      "kind": "tool",
      "name": "@zack/m19-search",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "tool:@zack/m19-comment@0.1.0": {
      "kind": "tool",
      "name": "@zack/m19-comment",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "skill:@zack/m19-skill@0.1.0": {
      "kind": "skill",
      "name": "@zack/m19-skill",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "knowledge:@zack/m19-guide@0.1.0": {
      "kind": "knowledge",
      "name": "@zack/m19-guide",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "memory:@zack/m19-memory@0.1.0": {
      "kind": "memory",
      "name": "@zack/m19-memory",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "profile:@zack/m19-style@0.1.0": {
      "kind": "profile",
      "name": "@zack/m19-style",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    },
    "loop:@zack/m19-loop@0.1.0": {
      "kind": "loop",
      "name": "@zack/m19-loop",
      "version": "0.1.0",
      "integrity": "sha256-m19"
    }
  },
  "roots": {
    "local:agent": {
      "name": "@zack/m19-tui-agent",
      "version": "0.1.0",
      "tools": [
        "tool:@zack/m19-search@0.1.0",
        "tool:@zack/m19-comment@0.1.0"
      ],
      "skills": ["skill:@zack/m19-skill@0.1.0"],
      "knowledge": ["knowledge:@zack/m19-guide@0.1.0"],
      "memory": ["memory:@zack/m19-memory@0.1.0"],
      "profiles": ["profile:@zack/m19-style@0.1.0"],
      "loop": "loop:@zack/m19-loop@0.1.0"
    }
  }
}
JSON

cp -R "$WORK" "$DIAGNOSTICS_WORK"
python3 - "$DIAGNOSTICS_WORK/agentpm.harness.json" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
config = json.loads(path.read_text())
config["runtime"]["state_dir"] = ".agentpm-state-m19-diagnostics"
config["ui"]["branding"]["subtitle"] = "M19 diagnostics fixture"
path.write_text(json.dumps(config, indent=2) + "\n")
PY

write_json "$(pkg_root_at "$DIAGNOSTICS_WORK" tools zack m19-env-check 0.1.0)/agent.json" <<'JSON'
{
  "kind": "tool",
  "name": "@zack/m19-env-check",
  "version": "0.1.0",
  "description": "M19 diagnostic fixture tool with required environment variables.",
  "entrypoint": {
    "command": "python3",
    "args": ["tool.py"],
    "cwd": ".",
    "timeout_ms": 1000,
    "env": {}
  },
  "environment": {
    "vars": {
      "M19_REQUIRED_TOKEN": {
        "required": true,
        "description": "Required manual test token."
      },
      "M19_REQUIRED_ENDPOINT": {
        "required": true,
        "description": "Required manual test endpoint."
      }
    }
  },
  "inputs": {
    "type": "object",
    "properties": {
      "query": { "type": "string" }
    }
  },
  "outputs": { "type": "object" }
}
JSON
cat >"$(pkg_root_at "$DIAGNOSTICS_WORK" tools zack m19-env-check 0.1.0)/tool.py" <<'PY'
import json, sys
payload = json.load(sys.stdin)
print(json.dumps({"ok": True, "input": payload}))
PY

write_json "$(pkg_root_at "$DIAGNOSTICS_WORK" tools zack m19-python-99 0.1.0)/agent.json" <<'JSON'
{
  "kind": "tool",
  "name": "@zack/m19-python-99",
  "version": "0.1.0",
  "description": "M19 diagnostic fixture tool with an intentionally impossible Python runtime requirement.",
  "runtime": {
    "type": "python",
    "version": "99.0.0"
  },
  "entrypoint": {
    "command": "python3",
    "args": ["tool.py"],
    "cwd": ".",
    "timeout_ms": 1000,
    "env": {}
  },
  "inputs": {
    "type": "object",
    "properties": {
      "query": { "type": "string" }
    }
  },
  "outputs": { "type": "object" }
}
JSON
cat >"$(pkg_root_at "$DIAGNOSTICS_WORK" tools zack m19-python-99 0.1.0)/tool.py" <<'PY'
import json, sys
payload = json.load(sys.stdin)
print(json.dumps({"ok": True, "input": payload}))
PY

write_json "$DIAGNOSTICS_WORK/agent.json" <<'JSON'
{
  "kind": "agent",
  "name": "@zack/m19-tui-agent",
  "version": "0.1.0",
  "description": "Manual fixture Agent for the M19 TUI shell with diagnostic tools.",
  "tools": [
    "@zack/m19-search@0.1.0",
    "@zack/m19-comment@0.1.0",
    "@zack/m19-env-check@0.1.0",
    "@zack/m19-python-99@0.1.0"
  ],
  "skills": ["@zack/m19-skill@0.1.0"],
  "knowledge": ["@zack/m19-guide@0.1.0"],
  "memory": ["@zack/m19-memory@0.1.0"],
  "profiles": ["@zack/m19-style@0.1.0"],
  "loop": "@zack/m19-loop@0.1.0",
  "bindings": {
    "consumer_context": { "file": "context.md" },
    "global": {
      "knowledge": ["@zack/m19-guide"],
      "profiles": ["@zack/m19-style"],
      "skills": ["@zack/m19-skill"],
      "memory": [
        { "package": "@zack/m19-memory", "spaces": ["current_note"] }
      ]
    },
    "phases": {
      "inspect": {
        "tools": [
          "@zack/m19-search",
          "@zack/m19-env-check",
          "@zack/m19-python-99"
        ]
      },
      "respond": { "tools": ["@zack/m19-comment"] }
    },
    "mcp": [
      { "id": "public-tools", "tools": ["@zack/m19-search", "@zack/m19-env-check"] }
    ]
  }
}
JSON

python3 - "$DIAGNOSTICS_WORK/agent.lock" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
lock = json.loads(path.read_text())
lock["packages"]["tool:@zack/m19-env-check@0.1.0"] = {
    "kind": "tool",
    "name": "@zack/m19-env-check",
    "version": "0.1.0",
    "integrity": "sha256-m19"
}
lock["packages"]["tool:@zack/m19-python-99@0.1.0"] = {
    "kind": "tool",
    "name": "@zack/m19-python-99",
    "version": "0.1.0",
    "integrity": "sha256-m19"
}
root = lock["roots"]["local:agent"]
root["tools"] = [
    "tool:@zack/m19-search@0.1.0",
    "tool:@zack/m19-comment@0.1.0",
    "tool:@zack/m19-env-check@0.1.0",
    "tool:@zack/m19-python-99@0.1.0",
]
path.write_text(json.dumps(lock, indent=2) + "\n")
PY

cp -R "$WORK" "$MISSING_SCOPE_WORK"
python3 - "$MISSING_SCOPE_WORK/agentpm.harness.json" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
config = json.loads(path.read_text())
config["runtime"]["state_dir"] = ".agentpm-state-m19-missing-scope"
config["ui"]["branding"]["subtitle"] = "M19 missing scope fixture"
config["scopes"] = {}
path.write_text(json.dumps(config, indent=2) + "\n")
PY

cp -R "$WORK" "$MISSING_MODEL_WORK"
python3 - "$MISSING_MODEL_WORK/agentpm.harness.json" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
config = json.loads(path.read_text())
config["runtime"]["state_dir"] = ".agentpm-state-m19-missing-model"
config["ui"]["branding"]["subtitle"] = "M19 missing model fixture"
config.pop("model", None)
path.write_text(json.dumps(config, indent=2) + "\n")
PY

cp -R "$WORK" "$SELECTION_WORK"
mkdir -p "$SELECTION_WORK/agents"
python3 - "$SELECTION_WORK/agentpm.harness.json" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
config = json.loads(path.read_text())
config["runtime"]["state_dir"] = ".agentpm-state-m19-selection"
config["ui"]["branding"]["subtitle"] = "M19 agent selection fixture"
path.write_text(json.dumps(config, indent=2) + "\n")
PY
write_json "$SELECTION_WORK/agents/alt.agent.json" <<'JSON'
{
  "kind": "agent",
  "name": "@zack/m19-alt-agent",
  "version": "0.1.0",
  "description": "Alternate Agent root used to test TUI Agent selection.",
  "tools": ["@zack/m19-search@0.1.0"],
  "loop": "@zack/m19-loop@0.1.0",
  "bindings": {
    "phases": {
      "inspect": { "tools": ["@zack/m19-search"] }
    }
  }
}
JSON
python3 - "$SELECTION_WORK/agent.lock" <<'PY'
import copy
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
lock = json.loads(path.read_text())
primary = lock["roots"]["local:agent"]
alt = copy.deepcopy(primary)
alt["name"] = "@zack/m19-alt-agent"
alt["version"] = "0.1.0"
alt["tools"] = ["tool:@zack/m19-search@0.1.0"]
alt.pop("skills", None)
alt.pop("knowledge", None)
alt.pop("memory", None)
alt.pop("profiles", None)
lock["roots"]["local:agent:agents/alt.agent.json"] = alt
path.write_text(json.dumps(lock, indent=2) + "\n")
PY

cat <<EOF
Created $ROOT/harness-m19-test

Run:
  source harness-m19-test/env.sh
  cargo build -p agentpm-cli
  (cd "\$M19_WORK" && "\$APM" harness)

Additional cases:
  (cd "\$M19_DIAGNOSTICS_WORK" && "\$APM" harness)
  (cd "\$M19_MISSING_SCOPE_WORK" && "\$APM" harness)
  (cd "\$M19_MISSING_MODEL_WORK" && "\$APM" harness)
  (cd "\$M19_SELECTION_WORK" && "\$APM" harness)

Exit the TUI with q or Esc.
EOF
