#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APM_BIN="$ROOT/target/debug/agentpm"
BASE="$ROOT/harness-m20a-test"
WORK="$BASE/workspace"
BUDGET_WORK="$BASE/budget-workspace"
OUTCOME_WORK="$BASE/outcome-workspace"
QUALITY_WORK="$BASE/quality-workspace"
RUNS="$BASE/runs"
PYTHON_CMD="${AGENTPM_MANUAL_PYTHON:-python3}"

pkg_root_at() {
  local workspace="$1"
  local kind="$2"
  local owner="$3"
  local name="$4"
  local version="$5"
  printf '%s/.agentpm/%s/%s/%s/%s' "$workspace" "$kind" "$owner" "$name" "$version"
}

pkg_root() {
  pkg_root_at "$WORK" "$@"
}

write_json() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat >"$path"
}

rm -rf "$BASE"
mkdir -p "$WORK/scripts" "$RUNS"

cat >"$BASE/env.sh" <<SH
export M20A_ROOT="$BASE"
export M20A_WORK="$WORK"
export M20A_BUDGET_WORK="$BUDGET_WORK"
export M20A_OUTCOME_WORK="$OUTCOME_WORK"
export M20A_QUALITY_WORK="$QUALITY_WORK"
export M20A_RUNS="$RUNS"
export APM="$APM_BIN"
export AGENTPM_MANUAL_PYTHON="\${AGENTPM_MANUAL_PYTHON:-$PYTHON_CMD}"
SH

cat >"$BASE/README.md" <<'MD'
# Harness M20A Manual Workspace

Generated by `scripts/setup-harness-m20a-manual.sh`.

See `HARNESS_M20A_MANUAL_TESTS.md` at the repo root for commands and expected evidence.

The workspace includes:

- deterministic OpenAI/Anthropic capture tests for required tool choice and phase-output fallback
- a deterministic long-output budget fixture
- an outcome-routing fixture with competing authored outcome descriptions
- a high-authoring-quality variant of the objective fixture with identical tool availability
- live OpenAI/Anthropic measurement commands for the Milestone 20A/20A.1 measurement checklist

Generated run output goes under `harness-m20a-test/runs/`.
MD

cat >"$WORK/context.md" <<'MD'
# M20A Manual Context

Use Harness phase outputs carefully. If a previous phase already reached a conclusion, preserve that conclusion rather than silently producing an empty phase result.
MD

write_json "$WORK/agentpm.m20a.openai.harness.json" <<'JSON'
{
  "version": 1,
  "model": {
    "provider": "openai",
    "model": "gpt-4o-mini"
  },
  "scopes": {
    "user": "m20a-user-openai"
  },
  "runtime": {
    "state_dir": ".agentpm-state-m20a-openai",
    "limits": {
      "max_steps": 8,
      "max_model_calls_per_phase": 6,
      "max_tool_calls_per_phase": 4,
      "max_actions_per_phase": 12,
      "max_structured_output_repairs": 2,
      "max_tool_call_repairs": 2
    }
  },
  "trace": {
    "enabled": true,
    "level": "verbose",
    "content": "full"
  }
}
JSON

write_json "$WORK/agentpm.m20a.anthropic.harness.json" <<'JSON'
{
  "version": 1,
  "model": {
    "provider": "anthropic",
    "model": "claude-haiku-4-5-20251001"
  },
  "scopes": {
    "user": "m20a-user-anthropic"
  },
  "runtime": {
    "state_dir": ".agentpm-state-m20a-anthropic",
    "limits": {
      "max_steps": 8,
      "max_model_calls_per_phase": 6,
      "max_tool_calls_per_phase": 4,
      "max_actions_per_phase": 12,
      "max_structured_output_repairs": 2,
      "max_tool_call_repairs": 2
    }
  },
  "trace": {
    "enabled": true,
    "level": "verbose",
    "content": "full"
  }
}
JSON

write_json "$WORK/agent.json" <<'JSON'
{
  "kind": "agent",
  "name": "m20a-output-agent",
  "version": "0.1.0",
  "description": "Manual fixture Agent for M20A phase output preservation.",
  "tools": ["@zack/m20a-search@0.1.0", "@zack/m20a-comment@0.1.0"],
  "loop": "@zack/m20a-output-loop@0.1.0",
  "bindings": {
    "consumer_context": { "file": "context.md" },
    "global": {},
    "phases": {
      "inspect": { "tools": ["@zack/m20a-search"] },
      "respond": { "tools": ["@zack/m20a-search", "@zack/m20a-comment"] }
    }
  }
}
JSON

write_json "$(pkg_root loops zack m20a-output-loop 0.1.0)/agent.json" <<'JSON'
{
  "kind": "loop",
  "name": "@zack/m20a-output-loop",
  "version": "0.1.0",
  "description": "Two-phase M20A output preservation loop.",
  "loop": {
    "entry_phase": "inspect",
    "phases": [
      {
        "id": "inspect",
        "objective": "Inspect the request and determine the concise answer or finding.",
        "outcomes": [
          { "id": "respond", "description": "Continue to the response phase." }
        ]
      },
      {
        "id": "respond",
        "objective": "Respond using the prior phase result when it already contains the answer.",
        "outcomes": [
          { "id": "done", "description": "Finish the run." }
        ]
      }
    ],
    "transitions": [
      { "from": "inspect", "on": "respond", "to": "respond" },
      { "from": "respond", "on": "done", "to": "$end" }
    ]
  }
}
JSON

for tool in m20a-search m20a-comment; do
  write_json "$(pkg_root tools zack "$tool" 0.1.0)/agent.json" <<JSON
{
  "kind": "tool",
  "name": "@zack/$tool",
  "version": "0.1.0",
  "description": "Manual M20A fixture tool.",
  "entrypoint": {
    "command": "$PYTHON_CMD",
    "args": ["tool.py"],
    "cwd": ".",
    "timeout_ms": 1000,
    "env": {}
  },
  "inputs": {
    "type": "object",
    "additionalProperties": false,
    "required": ["query"],
    "properties": {
      "query": { "type": "string" }
    }
  },
  "outputs": {
    "type": "object",
    "additionalProperties": true
  }
}
JSON
  cat >"$(pkg_root tools zack "$tool" 0.1.0)/tool.py" <<PY
import json
import sys
payload = json.load(sys.stdin)
print(json.dumps({"ok": True, "tool": "@zack/$tool", "input": payload, "result": "No relevant information found for " + payload.get("query", "")}))
PY
done

write_json "$WORK/agent.lock" <<'JSON'
{
  "lockfile_version": 3,
  "generated": "2026-09-22T00:00:00Z",
  "packages": {
    "tool:@zack/m20a-search@0.1.0": {
      "kind": "tool",
      "name": "@zack/m20a-search",
      "version": "0.1.0",
      "integrity": "sha256-m20a"
    },
    "tool:@zack/m20a-comment@0.1.0": {
      "kind": "tool",
      "name": "@zack/m20a-comment",
      "version": "0.1.0",
      "integrity": "sha256-m20a"
    },
    "loop:@zack/m20a-output-loop@0.1.0": {
      "kind": "loop",
      "name": "@zack/m20a-output-loop",
      "version": "0.1.0",
      "integrity": "sha256-m20a"
    }
  },
  "roots": {
    "local:agent": {
      "name": "m20a-output-agent",
      "version": "0.1.0",
      "tools": [
        "tool:@zack/m20a-search@0.1.0",
        "tool:@zack/m20a-comment@0.1.0"
      ],
      "loop": "loop:@zack/m20a-output-loop@0.1.0"
    }
  }
}
JSON

cp -R "$WORK" "$BUDGET_WORK"
python3 - "$BUDGET_WORK" <<'PY'
import json
import sys
from pathlib import Path

root = Path(sys.argv[1])
for config_name, state_dir in [
    ("agentpm.m20a.openai.harness.json", ".agentpm-state-m20a-budget-openai"),
    ("agentpm.m20a.anthropic.harness.json", ".agentpm-state-m20a-budget-anthropic"),
]:
    path = root / config_name
    config = json.loads(path.read_text())
    config["runtime"]["state_dir"] = state_dir
    config["runtime"]["limits"]["max_steps"] = 8
    path.write_text(json.dumps(config, indent=2) + "\n")

loop_path = root / ".agentpm" / "loops" / "zack" / "m20a-output-loop" / "0.1.0" / "agent.json"
loop = json.loads(loop_path.read_text())
phases = []
transitions = []
for i in range(1, 7):
    phase = f"step{i}"
    outcome = "done" if i == 6 else "next"
    phases.append({
        "id": phase,
        "objective": f"Produce a verbose output payload for M20A budget measurement step {i}.",
        "outcomes": [{"id": outcome, "description": "Continue or finish."}],
    })
    transitions.append({
        "from": phase,
        "on": outcome,
        "to": "$end" if i == 6 else f"step{i + 1}",
    })
loop["loop"]["entry_phase"] = "step1"
loop["loop"]["phases"] = phases
loop["loop"]["transitions"] = transitions
loop_path.write_text(json.dumps(loop, indent=2) + "\n")

agent_path = root / "agent.json"
agent = json.loads(agent_path.read_text())
agent["name"] = "m20a-budget-agent"
agent["description"] = "Manual fixture Agent for M20A cross-phase budget markers."
agent["bindings"]["phases"] = {f"step{i}": {"tools": ["@zack/m20a-search"]} for i in range(1, 7)}
agent_path.write_text(json.dumps(agent, indent=2) + "\n")
PY

cp -R "$WORK" "$QUALITY_WORK"
"$PYTHON_CMD" - "$QUALITY_WORK" <<'PY'
import json
import sys
from pathlib import Path

root = Path(sys.argv[1])
for config_name, state_dir in [
    ("agentpm.m20a.openai.harness.json", ".agentpm-state-m20a-quality-openai"),
    ("agentpm.m20a.anthropic.harness.json", ".agentpm-state-m20a-quality-anthropic"),
]:
    path = root / config_name
    config = json.loads(path.read_text())
    config["runtime"]["state_dir"] = state_dir
    path.write_text(json.dumps(config, indent=2) + "\n")

loop_path = root / ".agentpm" / "loops" / "zack" / "m20a-output-loop" / "0.1.0" / "agent.json"
loop = json.loads(loop_path.read_text())
loop["description"] = "High-authoring-quality M20A objective fixture with unchanged tool availability."
loop["loop"]["phases"] = [
    {
        "id": "inspect",
        "objective": (
            "Investigate whether the agentpm new command is ready. Use the search tool if needed, "
            "then produce a phase output that preserves the evidence needed by the response phase: "
            "what was checked, what readiness evidence was found or not found, and whether readiness "
            "can be confirmed."
        ),
        "outcomes": [
            {
                "id": "respond",
                "description": (
                    "Continue to the response phase after the investigation has captured the facts "
                    "the final answer should convey."
                ),
            }
        ],
    },
    {
        "id": "respond",
        "objective": (
            "Write the final operator-facing answer from the inspect phase output. Do not re-investigate "
            "when the prior output already states what was checked and whether readiness can be confirmed."
        ),
        "outcomes": [
            {
                "id": "done",
                "description": (
                    "Finish the run after returning the answer using the prior phase evidence."
                ),
            }
        ],
    },
]
loop_path.write_text(json.dumps(loop, indent=2) + "\n")

agent_path = root / "agent.json"
agent = json.loads(agent_path.read_text())
agent["name"] = "m20a-quality-agent"
agent["description"] = "Manual fixture Agent for M20A.1 high-quality authoring measurement."
agent_path.write_text(json.dumps(agent, indent=2) + "\n")
PY

cp -R "$WORK" "$OUTCOME_WORK"
"$PYTHON_CMD" - "$OUTCOME_WORK" <<'PY'
import json
import sys
from pathlib import Path

root = Path(sys.argv[1])
for config_name, state_dir in [
    ("agentpm.m20a.openai.harness.json", ".agentpm-state-m20a-outcome-openai"),
    ("agentpm.m20a.anthropic.harness.json", ".agentpm-state-m20a-outcome-anthropic"),
]:
    path = root / config_name
    config = json.loads(path.read_text())
    config["runtime"]["state_dir"] = state_dir
    path.write_text(json.dumps(config, indent=2) + "\n")

loop_path = root / ".agentpm" / "loops" / "zack" / "m20a-output-loop" / "0.1.0" / "agent.json"
loop = json.loads(loop_path.read_text())
loop["description"] = "Outcome routing fixture for M20A.1 authored outcome descriptions."
loop["loop"]["entry_phase"] = "classify"
loop["loop"]["phases"] = [
    {
        "id": "classify",
        "objective": "Classify whether the operator request should be answered here, handed off, or blocked.",
        "outcomes": [
            {
                "id": "respond",
                "description": "Use this when the current agent owns the answer and can complete it directly."
            },
            {
                "id": "handoff",
                "description": "Use this when another owner should continue because the request is outside this agent's responsibility."
            },
            {
                "id": "blocked",
                "description": "Use this when required information or authorization is missing and no owner can proceed yet."
            }
        ],
    },
    {
        "id": "respond",
        "objective": "Write the final answer using the classify phase output.",
        "outcomes": [
            {
                "id": "done",
                "description": "Finish the run after providing the operator-facing response."
            }
        ],
    },
]
loop["loop"]["transitions"] = [
    {"from": "classify", "on": "respond", "to": "respond"},
    {"from": "classify", "on": "handoff", "to": "$handoff"},
    {"from": "classify", "on": "blocked", "to": "$abort"},
    {"from": "respond", "on": "done", "to": "$end"},
]
loop_path.write_text(json.dumps(loop, indent=2) + "\n")

agent_path = root / "agent.json"
agent = json.loads(agent_path.read_text())
agent["name"] = "m20a-outcome-agent"
agent["description"] = "Manual fixture Agent for M20A.1 outcome-description routing."
agent["bindings"]["phases"] = {
    "classify": {"tools": ["@zack/m20a-search"]},
    "respond": {"tools": ["@zack/m20a-comment"]},
}
agent_path.write_text(json.dumps(agent, indent=2) + "\n")
PY

cat >"$WORK/scripts/m20a_capture_server.py" <<'PY'
#!/usr/bin/env python3
import argparse
import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--host", default="127.0.0.1")
parser.add_argument("--port", type=int, required=True)
parser.add_argument("--log", required=True)
parser.add_argument("--provider", choices=["openai", "anthropic"], required=True)
parser.add_argument("--scenario", choices=["fallback", "budget"], required=True)
args = parser.parse_args()

log_path = Path(args.log)
log_path.parent.mkdir(parents=True, exist_ok=True)
sequence = 0

def write_log(path, body):
    global sequence
    sequence += 1
    with log_path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps({
            "sequence": sequence,
            "provider": args.provider,
            "scenario": args.scenario,
            "path": path,
            "body": body,
        }, sort_keys=True) + "\n")

def alias_for(body, prefix):
    for tool in body.get("tools") or []:
        name = ((tool.get("function") or {}).get("name") or "") if args.provider == "openai" else tool.get("name") or ""
        if name.startswith(prefix):
            return name
    raise RuntimeError(f"missing tool alias starting with {prefix}")

def phase_complete_outcomes(body):
    for tool in body.get("tools") or []:
        if args.provider == "openai":
            function = tool.get("function") or {}
            if function.get("name") != "phase_complete":
                continue
            schema = function.get("parameters") or {}
        else:
            if tool.get("name") != "phase_complete":
                continue
            schema = tool.get("input_schema") or {}
        outcome = ((schema.get("properties") or {}).get("outcome") or {})
        enum = outcome.get("enum") or []
        return [str(value) for value in enum]
    return []

def openai_tool_response(alias, call_id, arguments, text=None):
    return {
        "id": "chatcmpl-m20a-capture",
        "object": "chat.completion",
        "choices": [{
            "index": 0,
            "message": {
                "role": "assistant",
                "content": text,
                "tool_calls": [{
                    "id": call_id,
                    "type": "function",
                    "function": {"name": alias, "arguments": json.dumps(arguments)},
                }],
            },
            "finish_reason": "tool_calls",
        }],
        "usage": {"prompt_tokens": 1, "completion_tokens": 1, "total_tokens": 2},
    }

def anthropic_tool_response(alias, call_id, arguments, text=None):
    content = []
    if text:
        content.append({"type": "text", "text": text})
    content.append({"type": "tool_use", "id": call_id, "name": alias, "input": arguments})
    return {
        "id": "msg_m20a_capture",
        "type": "message",
        "role": "assistant",
        "content": content,
        "stop_reason": "tool_use",
        "usage": {"input_tokens": 1, "output_tokens": 1},
    }

def tool_response(body, prefix, call_id, arguments, text=None):
    alias = alias_for(body, prefix)
    if args.provider == "openai":
        return openai_tool_response(alias, call_id, arguments, text)
    return anthropic_tool_response(alias, call_id, arguments, text)

def long_output(n):
    sentence = (
        f"M20A budget output step {n}: this intentionally verbose phase answer "
        "describes status, evidence, consequence, recommendation, and residual risk. "
    )
    return {"summary": sentence * 70}

def response_for(body):
    if args.scenario == "fallback":
        outcomes = phase_complete_outcomes(body)
        if "respond" in outcomes and "done" not in outcomes:
            return tool_response(
                body,
                "phase_complete",
                f"call_m20a_fallback_{sequence}",
                {"outcome": "respond"},
                "M20A fallback answer from completing assistant content.",
            )
        return tool_response(
            body,
            "phase_complete",
            f"call_m20a_done_{sequence}",
            {
                "outcome": "done",
                "output": {"summary": "M20A terminal output survived from canonical phase output."},
            },
        )
    if args.scenario == "budget":
        outcome = "done" if sequence >= 6 else "next"
        return tool_response(
            body,
            "phase_complete",
            f"call_m20a_budget_{sequence}",
            {"outcome": outcome, "output": long_output(sequence)},
        )
    raise RuntimeError("unknown scenario")

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/health":
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"ok")
            return
        self.send_response(404)
        self.end_headers()

    def do_POST(self):
        length = int(self.headers.get("content-length", "0"))
        body = json.loads(self.rfile.read(length) or b"{}")
        write_log(self.path, body)
        try:
            response = response_for(body)
            payload = json.dumps(response).encode()
            self.send_response(200)
        except Exception as exc:
            payload = json.dumps({"error": str(exc)}).encode()
            self.send_response(500)
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt, *values):
        return

ThreadingHTTPServer((args.host, args.port), Handler).serve_forever()
PY
chmod +x "$WORK/scripts/m20a_capture_server.py"
cp "$WORK/scripts/m20a_capture_server.py" "$BUDGET_WORK/scripts/m20a_capture_server.py"
cp "$WORK/scripts/m20a_capture_server.py" "$OUTCOME_WORK/scripts/m20a_capture_server.py"
cp "$WORK/scripts/m20a_capture_server.py" "$QUALITY_WORK/scripts/m20a_capture_server.py"

cat >"$WORK/scripts/m20a_assert_capture.py" <<'PY'
#!/usr/bin/env python3
import json
import sys
from pathlib import Path

if len(sys.argv) != 4:
    raise SystemExit("usage: m20a_assert_capture.py BODIES_JSONL PROVIDER SCENARIO")

path = Path(sys.argv[1])
provider = sys.argv[2]
scenario = sys.argv[3]
rows = [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
if not rows:
    raise SystemExit("capture server recorded no provider bodies")
bodies = [row["body"] for row in rows]
first = bodies[0]

if provider == "openai":
    if first.get("tool_choice") != "required":
        raise SystemExit(f"expected OpenAI tool_choice=required, got {first.get('tool_choice')!r}")
    tools = [((tool.get("function") or {}).get("name"), tool) for tool in first.get("tools") or []]
else:
    if first.get("tool_choice") != {"type": "any"}:
        raise SystemExit(f"expected Anthropic tool_choice={{'type':'any'}}, got {first.get('tool_choice')!r}")
    tools = [(tool.get("name"), tool) for tool in first.get("tools") or []]

phase_tools = [tool for name, tool in tools if name == "phase_complete"]
if not phase_tools:
    raise SystemExit("phase_complete tool was not advertised")
tool_text = json.dumps(phase_tools[0])
if "include" not in tool_text.lower() or "output" not in tool_text.lower():
    raise SystemExit("phase_complete schema/description does not mention including output")

body_text = json.dumps(first)
for expected in [
    "Execution model: This is one phase of one Run.",
    "Phase boundary: this phase's working transcript is local.",
    "Current phase:",
]:
    if expected not in body_text:
        raise SystemExit(f"provider body missing prompt contract text: {expected}")
if scenario == "fallback":
    for expected in [
        "`respond`: Continue to the response phase.",
        "This phase must complete with exactly one authored outcome.",
    ]:
        if expected not in body_text:
            raise SystemExit(f"provider body missing authored outcome text: {expected}")

if scenario == "budget" and len(bodies) > 1:
    later_text = "\n".join(json.dumps(body) for body in bodies[1:])
    for expected in [
        "[cross-phase state: compact handoff from earlier phases, not their transcripts.",
        "Prior outputs carry conclusions forward",
    ]:
        if expected not in later_text:
            raise SystemExit(f"later provider body missing cross-phase state semantics: {expected}")

print(f"ok: {provider} {scenario} required tool choice, phase_complete output guidance, and prompt contract text present")
print(f"captured bodies: {path}")
PY
chmod +x "$WORK/scripts/m20a_assert_capture.py"
cp "$WORK/scripts/m20a_assert_capture.py" "$BUDGET_WORK/scripts/m20a_assert_capture.py"
cp "$WORK/scripts/m20a_assert_capture.py" "$OUTCOME_WORK/scripts/m20a_assert_capture.py"
cp "$WORK/scripts/m20a_assert_capture.py" "$QUALITY_WORK/scripts/m20a_assert_capture.py"

cat >"$WORK/scripts/m20a_analyze_trace.py" <<'PY'
#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

def stable_json(value: Any) -> str:
    return json.dumps(value if value is not None else {}, sort_keys=True, separators=(",", ":"))

def load_events(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]

RUNTIME_FIELD_KEYS = {
    "attempt",
    "error",
    "provider_alias",
    "provider_call_id",
    "result",
    "source",
}

def model_argument_fields(event: dict[str, Any]) -> dict[str, Any]:
    fields = (event.get("payload") or {}).get("fields") or {}
    if isinstance(fields.get("arguments"), dict):
        return fields["arguments"]
    return {
        key: value
        for key, value in fields.items()
        if key not in RUNTIME_FIELD_KEYS
    }

def action_key(event: dict[str, Any]) -> tuple[str, str, str] | None:
    payload = event.get("payload") or {}
    if payload.get("payload_type") != "action":
        return None
    kind = payload.get("action_kind")
    identity = payload.get("identity")
    if not kind or not identity or kind == "phase_completion":
        return None
    return str(kind), str(identity), stable_json(model_argument_fields(event))

def action_identity_key(event: dict[str, Any]) -> tuple[str, str] | None:
    payload = event.get("payload") or {}
    if payload.get("payload_type") != "action":
        return None
    kind = payload.get("action_kind")
    identity = payload.get("identity")
    if not kind or not identity or kind == "phase_completion":
        return None
    return str(kind), str(identity)

def proposed_phase_completions(fields: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        action
        for action in fields.get("proposed_actions") or []
        if action.get("action_kind") == "phase_completion"
    ]

COMPLETED_EVENTS = {
    "knowledge_retrieved",
    "mcp_tool_completed",
    "memory_read_completed",
    "memory_write_completed",
    "semantic_action_completed",
    "skill_resource_loaded",
    "tool_completed",
}

FAILED_EVENTS = {
    "knowledge_failed",
    "mcp_tool_failed",
    "memory_read_failed",
    "memory_write_failed",
    "semantic_action_failed",
    "skill_resource_failed",
    "tool_failed",
}

def summarize(events: list[dict[str, Any]]) -> dict[str, Any]:
    by_phase: dict[str, Counter[tuple[str, str, str]]] = defaultdict(Counter)
    seen_phase_for_action: dict[tuple[str, str, str], set[str]] = defaultdict(set)
    by_phase_identity: dict[str, dict[tuple[str, str], Counter[str]]] = defaultdict(lambda: defaultdict(Counter))
    seen_phase_for_identity: dict[tuple[str, str], dict[str, Counter[str]]] = defaultdict(lambda: defaultdict(Counter))
    action_status_by_phase: dict[str, dict[tuple[str, str, str], str]] = defaultdict(dict)
    prior_status_by_action: dict[tuple[str, str, str], list[str]] = defaultdict(list)
    repairs = Counter()
    fallback = Counter()
    budget_headers = Counter()
    outcome_distribution = Counter()
    successful_cross_repeats = 0
    failed_cross_repeats = 0
    counters = Counter()

    for event in events:
        event_type = event.get("event_type")
        payload = event.get("payload") or {}
        fields = payload.get("fields") or {}
        phase_id = event.get("phase_execution_id") or "no-phase"

        if event_type == "semantic_action_proposed":
            key = action_key(event)
            if key:
                by_phase[str(phase_id)][key] += 1
                prior_statuses = prior_status_by_action.get(key, [])
                if "completed" in prior_statuses:
                    successful_cross_repeats += 1
                elif "failed" in prior_statuses:
                    failed_cross_repeats += 1
                seen_phase_for_action[key].add(str(phase_id))
            identity_key = action_identity_key(event)
            if identity_key:
                fields_key = stable_json(model_argument_fields(event))
                by_phase_identity[str(phase_id)][identity_key][fields_key] += 1
                seen_phase_for_identity[identity_key][str(phase_id)][fields_key] += 1
        elif event_type in COMPLETED_EVENTS | FAILED_EVENTS:
            key = action_key(event)
            if key:
                action_status_by_phase[str(phase_id)][key] = (
                    "completed" if event_type in COMPLETED_EVENTS else "failed"
                )
        elif event_type == "phase_result_ready":
            phase_payload_id = payload.get("phase_id") or "unknown"
            outcome = payload.get("outcome") or "unknown"
            outcome_distribution[f"{phase_payload_id}:{outcome}"] += 1
            for key, status in action_status_by_phase.pop(str(phase_id), {}).items():
                prior_status_by_action[key].append(status)
            if payload.get("output") is None:
                counters["phase_result_null_outputs"] += 1
            else:
                counters["phase_result_outputs"] += 1
        elif event_type == "run_completed":
            if payload.get("output") is None:
                counters["run_completed_null_outputs"] += 1
            else:
                counters["run_completed_outputs"] += 1
        elif event_type == "model_repair_requested":
            counters["model_repair_requested"] += 1
            repairs[str(fields.get("repair_kind") or "unknown")] += 1
        elif event_type == "phase_output_fallback":
            fallback[f"{payload.get('status')}:{payload.get('source')}"] += 1
        elif event_type == "model_request_completed":
            completions = proposed_phase_completions(fields)
            if completions:
                counters["completing_turns"] += len(completions)
                if fields.get("assistant_content"):
                    counters["completing_turns_with_assistant_content"] += len(completions)
                for action in completions:
                    action_fields = action.get("fields") or {}
                    if action_fields.get("output") is None:
                        counters["phase_completion_without_output"] += 1
                    else:
                        counters["phase_completion_with_output"] += 1
        elif event_type == "prompt_prepared":
            prompt = fields.get("prompt") or ""
            if "[cross-phase detail budget:" in prompt:
                counters["section4_budget_prompts"] += 1
                for header in re.findall(r"\[cross-phase detail budget:[^\]]+\]", prompt):
                    budget_headers[header] += 1
            if "[cross-phase output detail marker:" in prompt:
                counters["section4_budget_marker_prompts"] += 1
            counters["section4_output_stub_markers"] += prompt.count("output: [omitted:")

    within_repeats = 0
    for counter in by_phase.values():
        within_repeats += sum(count - 1 for count in counter.values() if count > 1)
    cross_repeats = 0
    for phases in seen_phase_for_action.values():
        if len(phases) > 1:
            cross_repeats += len(phases) - 1
    within_same_action_rework = 0
    within_changed_argument_rework = 0
    for actions in by_phase_identity.values():
        for fields_counter in actions.values():
            total = sum(fields_counter.values())
            if total > 1:
                within_same_action_rework += total - 1
            if len(fields_counter) > 1:
                within_changed_argument_rework += total - max(fields_counter.values())
    cross_same_action_rework = 0
    cross_changed_argument_rework = 0
    for phases in seen_phase_for_identity.values():
        if len(phases) > 1:
            cross_same_action_rework += len(phases) - 1
            all_fields = set()
            for fields_counter in phases.values():
                all_fields.update(fields_counter)
            if len(all_fields) > 1:
                cross_changed_argument_rework += len(phases) - 1

    return {
        "events": len(events),
        "within_phase_exact_repeats": within_repeats,
        "cross_phase_exact_repeats": cross_repeats,
        "within_phase_same_action_rework": within_same_action_rework,
        "within_phase_changed_argument_rework": within_changed_argument_rework,
        "cross_phase_same_action_rework": cross_same_action_rework,
        "cross_phase_changed_argument_rework": cross_changed_argument_rework,
        "cross_phase_repeats_after_success": successful_cross_repeats,
        "cross_phase_repeats_after_failure": failed_cross_repeats,
        **dict(counters),
        "outcome_distribution": dict(sorted(outcome_distribution.items())),
        "section4_budget_headers": dict(budget_headers),
        "repairs_by_kind": dict(repairs),
        "phase_output_fallback": dict(fallback),
    }

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("events_jsonl", type=Path)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    summary = summarize(load_events(args.events_jsonl))
    if args.json:
        print(json.dumps(summary, indent=2, sort_keys=True))
        return
    for key in sorted(summary):
        value = summary[key]
        if isinstance(value, dict):
            print(f"{key}: {json.dumps(value, sort_keys=True)}")
        else:
            print(f"{key}: {value}")

if __name__ == "__main__":
    main()
PY
chmod +x "$WORK/scripts/m20a_analyze_trace.py"
cp "$WORK/scripts/m20a_analyze_trace.py" "$BUDGET_WORK/scripts/m20a_analyze_trace.py"
cp "$WORK/scripts/m20a_analyze_trace.py" "$OUTCOME_WORK/scripts/m20a_analyze_trace.py"
cp "$WORK/scripts/m20a_analyze_trace.py" "$QUALITY_WORK/scripts/m20a_analyze_trace.py"

cat >"$WORK/scripts/m20a_analyze_trace_selftest.py" <<'PY'
#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
from pathlib import Path

module_path = Path(__file__).with_name("m20a_analyze_trace.py")
spec = importlib.util.spec_from_file_location("m20a_analyze_trace", module_path)
if spec is None or spec.loader is None:
    raise SystemExit("unable to load m20a_analyze_trace.py")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

def action_event(event_type, phase, status, query, *, result=None):
    fields = {"arguments": {"query": query}, "source": "agent_binding"}
    if result is not None:
        fields.update({"attempt": 1, "result": result})
    return {
        "event_type": event_type,
        "phase_execution_id": phase,
        "payload": {
            "payload_type": "action",
            "action_kind": "agentpm_tool",
            "identity": "@zack/m20a-search",
            "status": status,
            "fields": fields,
        },
    }

def phase_result(phase):
    return {
        "event_type": "phase_result_ready",
        "phase_execution_id": phase,
        "payload": {
            "payload_type": "phase",
            "phase_id": phase,
            "outcome": "next",
            "output": {"ok": True},
        },
    }

events = [
    action_event("semantic_action_proposed", "phase-exec-1", "accepted", "agentpm new"),
    action_event("tool_completed", "phase-exec-1", "completed", "agentpm new", result={"ok": True}),
    phase_result("phase-exec-1"),
    action_event("semantic_action_proposed", "phase-exec-2", "accepted", "agentpm new"),
    action_event("tool_completed", "phase-exec-2", "completed", "agentpm new", result={"ok": True}),
    phase_result("phase-exec-2"),
    action_event("semantic_action_proposed", "phase-exec-3", "accepted", "agentpm failed"),
    action_event("tool_failed", "phase-exec-3", "failed", "agentpm failed", result={"ok": False}),
    phase_result("phase-exec-3"),
    action_event("semantic_action_proposed", "phase-exec-4", "accepted", "agentpm failed"),
]
summary = module.summarize(events)
assert summary["cross_phase_exact_repeats"] == 2, summary
assert summary["cross_phase_repeats_after_success"] == 1, summary
assert summary["cross_phase_repeats_after_failure"] == 1, summary
print("m20a_analyze_trace_selftest: ok")
PY
chmod +x "$WORK/scripts/m20a_analyze_trace_selftest.py"
cp "$WORK/scripts/m20a_analyze_trace_selftest.py" "$BUDGET_WORK/scripts/m20a_analyze_trace_selftest.py"
cp "$WORK/scripts/m20a_analyze_trace_selftest.py" "$OUTCOME_WORK/scripts/m20a_analyze_trace_selftest.py"
cp "$WORK/scripts/m20a_analyze_trace_selftest.py" "$QUALITY_WORK/scripts/m20a_analyze_trace_selftest.py"

if [ -x "$APM_BIN" ]; then
  "$APM_BIN" lint "$WORK/agent.json" >/dev/null
  "$APM_BIN" lint "$BUDGET_WORK/agent.json" >/dev/null
  "$APM_BIN" lint "$OUTCOME_WORK/agent.json" >/dev/null
  "$APM_BIN" lint "$QUALITY_WORK/agent.json" >/dev/null
fi

cat <<MSG
Harness M20A manual workspace generated.
  root:       $BASE
  workspace:  $WORK
  budget:     $BUDGET_WORK
  outcome:    $OUTCOME_WORK
  quality:    $QUALITY_WORK
  runs:       $RUNS

Next:
  source harness-m20a-test/env.sh
  open HARNESS_M20A_MANUAL_TESTS.md for test commands
MSG
